# Generated by Django 3.1 on 2020-08-24 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('op_type', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('is_terminated', models.BooleanField(default=False)),
                ('lines_finished', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_file', to='csvfile.file')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='op',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_op', to='csvfile.operation'),
        ),
    ]
