# Generated by Django 3.1 on 2020-08-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
